server:
  port: 8084

spring:
  application:
    name: audit-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: audit-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer